version: '3.8'

services:
  custom-detection-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./test_results:/app/test_results
    environment:
      - MAX_WORKERS=4
      - CONFIDENCE_THRESHOLD=0.5
      - IOU_THRESHOLD=0.45
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 